--- 
title: "GO and KEGG analysis for MAPP paper"
author: "Ian U. Kouzel"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "GO and KEGG analysis for MAPP paper"
---

# Prerequisites

## Libraries 

```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(clusterProfiler)
library(pathview)
library(enrichplot)
library(org.Hs.eg.db)
library(readr)
library(DT)
library(matrixTests)
```

## Options 

```{r}
# These options are used for GO analysis in the downstream scripts /
# R markdown pages:

# minimal size of genes annotated by ontology term for testing
minGSSize <- 10 

# human DB
organismDB <- "org.Hs.eg.db"

# p-value cutoff
pvalueCutoff <- 0.1

# number of GOs to plot
showCategory <- 10 

# p-adjusted cut off for cassette exons that are different between 
# control and cancer conditions
genes_padj_cutoff <- 0.1
```

## Universe set of genes

**all genes having quantified cassette exons**

### GO (ENSEMBL)

```{r}
# read table with cassette exons and select the genes
universe <- read.table("data/cassette_exons_universe_table.tsv", 
                       header = T) %>% dplyr::select(gene_id) %>% unlist()

# select unique IDs
universe <- unique(unlist(strsplit(universe, ",")))

# preview first 10 entrees
head(universe, 10)

# length of a vector with ENSEMBL IDs
length(universe)  
```

### KEGG (ENTREZ)

```{r, warning = FALSE}
# convert ENSEMBL IDs into ENTREZ format (required for KEGG analysis)
ENTREZ_universe <- bitr(universe, fromType = "ENSEMBL", 
                        toType = "ENTREZID", OrgDb= organismDB) %>% 
                        dplyr::select(ENTREZID) %>% unlist()

# select unique IDs
ENTREZ_universe <- unique(unlist(strsplit(ENTREZ_universe, ",")))

# preview first 10 entrees
head(ENTREZ_universe)

# length of a vector with ENSEMBL IDs
length(ENTREZ_universe)  
```

## Render the book 

```{r, eval = F}
# the full book is rendered with this command
bookdown::render_book("index.Rmd", "bookdown::gitbook")
```

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

## Session info

```{r}
sessionInfo()
```

